#!/usr/bin/env bash
# Checks the generated docs/openapi.yaml against the pinned Valhalla tag and the local patch.
# Requires Docker; pulls yq and redocly.
set -euo pipefail

YQ_IMAGE="${YQ_IMAGE:-mikefarah/yq:4}"
REDOCLY_IMAGE="${REDOCLY_IMAGE:-redocly/cli:2.19.0}"

# Same Windows handling as nginx-auth.test.sh: native path for the bind mount, MSYS mangling
# disabled only around docker.
repo_root() {
  local dir
  dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
  if command -v cygpath >/dev/null 2>&1; then
    cygpath -m "${dir}"
  else
    printf '%s' "${dir}"
  fi
}
dkr() { MSYS_NO_PATHCONV=1 docker "$@"; }

REPO_ROOT="$(repo_root)"
SPEC_DIR="${REPO_ROOT}/docs"
SPEC_FILE="${SPEC_DIR}/openapi.yaml"
COMPOSE_FILE="${REPO_ROOT}/docker-compose.yml"

failures=0
pass() { printf 'PASS  %s\n' "$1"; }
fail() { printf 'FAIL  %s (expected %s, got %s)\n' "$1" "$2" "$3"; failures=$((failures + 1)); }
assert_eq() {
  local name="$1" expected="$2" actual="$3"
  if [[ "${expected}" == "${actual}" ]]; then pass "${name}"; else fail "${name}" "${expected}" "${actual}"; fi
}

yq_spec() { dkr run --rm -v "${SPEC_DIR}:/spec:ro" "${YQ_IMAGE}" "$1" /spec/openapi.yaml; }

if [[ ! -f "${SPEC_FILE}" ]]; then
  printf 'FAIL  spec missing: %s (run scripts/sync-openapi.sh)\n' "${SPEC_FILE}"
  exit 1
fi

# Bash regex keeps the test free of tools the CI runner and the EC2 host do not have.
VALHALLA_TAG=""
if [[ "$(<"${COMPOSE_FILE}")" =~ valhalla-scripted:([^[:space:]]+) ]]; then
  VALHALLA_TAG="${BASH_REMATCH[1]}"
fi
if [[ -z "${VALHALLA_TAG}" ]]; then
  printf 'FAIL  could not read the Valhalla tag from %s\n' "${COMPOSE_FILE}"
  exit 1
fi

IFS= read -r first_line < "${SPEC_FILE}"
assert_eq "info.version matches the compose image tag" "${VALHALLA_TAG}" "$(yq_spec '.info.version')"
assert_eq "first line names the generator and the tag" \
  "# Generated by scripts/sync-openapi.sh from valhalla/valhalla@${VALHALLA_TAG}. Do not edit; edit openapi.patch.yaml." \
  "${first_line}"
assert_eq "/height removed" "null" "$(yq_spec '.paths."/height"')"
assert_eq "10 paths remain (11 upstream minus /height)" "10" "$(yq_spec '.paths | keys | length')"
assert_eq "ApiKeyAuth is a header scheme" "apiKey" "$(yq_spec '.components.securitySchemes.ApiKeyAuth.type')"
assert_eq "ApiKeyAuth.in == header" "header" "$(yq_spec '.components.securitySchemes.ApiKeyAuth.in')"
assert_eq "ApiKeyAuth.name == X-API-Key" "X-API-Key" "$(yq_spec '.components.securitySchemes.ApiKeyAuth.name')"
assert_eq "ApiKeyAuth applied globally" "true" "$(yq_spec '.security[0] | has("ApiKeyAuth")')"
assert_eq "exactly one server (upstream one replaced)" "1" "$(yq_spec '.servers | length')"
assert_eq "server is same-origin" "/" "$(yq_spec '.servers[0].url')"

# Lint with redocly's recommended ruleset; warnings are tolerated, errors are not.
if dkr run --rm -v "${SPEC_DIR}:/spec:ro" "${REDOCLY_IMAGE}" lint /spec/openapi.yaml --format=stylish; then
  pass "redocly lint has no errors"
else
  fail "redocly lint has no errors" "exit 0" "non-zero exit"
fi

if [[ "${failures}" -ne 0 ]]; then
  printf '\n%d assertion(s) failed\n' "${failures}"
  exit 1
fi
printf '\nall assertions passed\n'
