#!/usr/bin/env bash
# Regenerates docs/openapi.yaml: upstream spec at the compose-pinned Valhalla tag, merged
# with docs/openapi.patch.yaml. Re-run after bumping the tag; tests/openapi.test.sh enforces it.
set -euo pipefail

# shellcheck source=lib.sh
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

YQ_IMAGE="${YQ_IMAGE:-mikefarah/yq:4}"
UPSTREAM_PATH="docs/docs/api/openapi.yaml"
COMPOSE_FILE="${REPO_ROOT}/docker-compose.yml"
DOCS_DIR="${REPO_ROOT}/docs"
PATCH_FILE="${DOCS_DIR}/openapi.patch.yaml"
OUT_FILE="${DOCS_DIR}/openapi.yaml"

require_cmd curl
require_cmd docker

# Bash regex instead of rg/sd: the script must also work on the EC2 host with only coreutils.
if [[ ! "$(<"${COMPOSE_FILE}")" =~ valhalla-scripted:([^[:space:]]+) ]]; then
  echo "ERROR: no valhalla-scripted image tag found in ${COMPOSE_FILE}." >&2
  exit 1
fi
TAG="${BASH_REMATCH[1]}"

# Docker Desktop on Windows needs a native path for the bind mount and no MSYS path mangling.
mount_dir() {
  if command -v cygpath >/dev/null 2>&1; then cygpath -m "$1"; else printf '%s' "$1"; fi
}
dkr() { MSYS_NO_PATHCONV=1 docker "$@"; }

WORK_DIR="$(mktemp -d)"
trap 'rm -rf "${WORK_DIR}"' EXIT

echo "Fetching valhalla/valhalla@${TAG}:${UPSTREAM_PATH}"
curl -fsSL "https://raw.githubusercontent.com/valhalla/valhalla/${TAG}/${UPSTREAM_PATH}" \
  -o "${WORK_DIR}/upstream.yaml"
cp "${PATCH_FILE}" "${WORK_DIR}/patch.yaml"

# Upstream <= 3.8.3 nests the pedestrian options under `type` instead of `properties`
# (fixed by valhalla/valhalla#6255). Lifting them out is a no-op once the tag includes the fix.
SCHEMA_KEYWORDS='^(type|default|enum|description|x-enumDescriptions)$'
FIX_PEDESTRIAN='(.components.schemas.PedestrianCostingOptions.allOf[] | select(has("properties")) | .properties) |= (
  (.type | with_entries(select(.key | test("'"${SCHEMA_KEYWORDS}"'") | not))) as $moved
  | .type |= with_entries(select(.key | test("'"${SCHEMA_KEYWORDS}"'")))
  | . + $moved
)'

# The patch's own comments are stripped so they do not land mid-file; yq drops leading
# comments anyway, so the provenance header is prepended after the merge.
{
  printf '# Generated by scripts/sync-openapi.sh from valhalla/valhalla@%s. Do not edit; edit openapi.patch.yaml.\n' "${TAG}"
  dkr run --rm -v "$(mount_dir "${WORK_DIR}"):/w:ro" "${YQ_IMAGE}" eval-all \
    '(select(fileIndex==0) * (select(fileIndex==1) | ... comments=""))
     | del(.paths."/height") | del(.components.schemas.HeightRequest)
     | '"${FIX_PEDESTRIAN}"'
     | .info.version = "'"${TAG}"'"' \
    /w/upstream.yaml /w/patch.yaml
} > "${WORK_DIR}/openapi.yaml"

mv "${WORK_DIR}/openapi.yaml" "${OUT_FILE}"
echo "Wrote ${OUT_FILE} (valhalla ${TAG})"
